kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-discoverer
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "configmaps", "secrets", "pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-service-discoverer
  namespace: todolist
subjects:
  - kind: ServiceAccount
    name: default
    namespace: todolist
roleRef:
  kind: Role
  name: service-discoverer
  apiGroup: rbac.authorization.k8s.io
